trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '18.x'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(node_version)'
    displayName: 'Instalar Node.js'

  - script: |
      corepack enable
      corepack prepare pnpm@latest --activate
    displayName: 'Instalar pnpm'

  - script: |
      pnpm install
    displayName: 'Instalar dependencias'

  - script: |
      pnpm run build
    displayName: 'Construir aplicación Vite + React'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: 'flyblue-frontend'
    displayName: 'Publicar artefacto de compilación'
