# =========================================================
# PIPELINE ÚNICO CI/CD - FLYBLUE FRONTEND (VITE + REACT)
# =========================================================

trigger:
  branches:
    include:
      - dev
      - test
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: nodeVersion
    value: '18.x'
  - name: buildDir
    value: 'dist'
  - group: 'VG-FLYBLUE-FRONT'   # VARIABLE GROUP

stages:
  - stage: BuildAndDeploy
    displayName: 'Build & Deploy Frontend'
    jobs:

      # =====================================================
      # JOB 1 → BUILD
      # =====================================================
      - job: Build
        displayName: 'Build Frontend'
        steps:

          - task: NodeTool@0
            inputs:
              versionSpec: '$(nodeVersion)'
            displayName: 'Instalar Node.js'

          - script: |
              npm install
            displayName: 'Instalar dependencias'

          #  CREAR ARCHIVO .env.production SEGÚN LA RAMA
          - script: |
              echo "Branch detectada: $(Build.SourceBranch)"

              if [ "$(Build.SourceBranch)" = "refs/heads/dev" ]; then
                echo ">>> Variables DEV"
                echo "VITE_API_URL=$(VITE_API_URL_DEV)" > .env.production

              elif [ "$(Build.SourceBranch)" = "refs/heads/test" ]; then
                echo ">>> Variables TEST"
                echo "VITE_API_URL=$(VITE_API_URL_TEST)" > .env.production

              else
                echo ">>> Variables MAIN"
                echo "VITE_API_URL=$(VITE_API_URL_MAIN)" > .env.production
              fi

              echo "Archivo generado:"
              cat .env.production
            displayName: "Crear archivo .env.production con variables del entorno"

          # COMPILAR CON VITE USANDO ESAS VARIABLES
          - script: |
              npm run build --mode production
            displayName: 'Compilar con Vite'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/$(buildDir)'
              artifact: 'dist'
            displayName: 'Publicar artefacto compilado'

      # =====================================================
      # JOB 2 → DEPLOY
      # =====================================================
      - job: Deploy
        displayName: 'Desplegar a Azure Static Web App'
        dependsOn: Build
        steps:

          - download: current
            artifact: dist

          # SELECCIONA TOKEN CORRECTO
          - script: |
              echo "Branch detectada: $(Build.SourceBranch)"

              if [ "$(Build.SourceBranch)" = "refs/heads/dev" ]; then
                echo ">>> Deploy a DEV"
                echo "##vso[task.setvariable variable=DEPLOY_TOKEN]$(AZURE_STATIC_WEB_APP_TOKEN_DEV)"

              elif [ "$(Build.SourceBranch)" = "refs/heads/test" ]; then
                echo ">>> Deploy a TEST"
                echo "##vso[task.setvariable variable=DEPLOY_TOKEN]$(AZURE_STATIC_WEB_APP_TOKEN_TEST)"

              else
                echo ">>> Deploy a MAIN"
                echo "##vso[task.setvariable variable=DEPLOY_TOKEN]$(AZURE_STATIC_WEB_APP_TOKEN_MAIN)"
              fi
            displayName: 'Seleccionar token según la rama'

          - task: AzureStaticWebApp@0
            displayName: 'Deploy to Azure Static Web App'
            inputs:
              app_location: '/'
              output_location: 'dist'
              azure_static_web_apps_api_token: '$(DEPLOY_TOKEN)'

